### ISSUE TITLE
Reports not working in PHP 5.4

### ISSUE THREAD

**Issue by matt-west** [simpleinvoices/simpleinvoices#15]
Encountering the following error when attempting to generate reports.

Fatal error: Call-time pass-by-reference has been removed in /Users/mattwest/Projects/open-source/simpleinvoices/library/phpreports/PHPReportMaker.php(274) : eval()'d code on line 151

PHP v5.4.4

Monthly Sales and Payments report still works fine.

**Comment by Green-Guy** [comment]
Matt, 

How do I get the changes you made to not use phpreports? Thanks!
