### ISSUE TITLE
Deprecated: preg_replace(): Smarty_Compiler.class.php on line 270

### ISSUE THREAD

**Issue by xstable** [simpleinvoices/simpleinvoices#160]
Got this error on install the 2013.1.beta8:

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /library/smarty/Smarty_Compiler.class.php on line 270

Screenshot: http://i.imm.io/1n1TR.jpeg

Here is the fix 

Code:
        $source_content = preg_replace_callback($search, create_function ('$matches', "return '" 
                                       . $this->_quote_replace($this->left_delimiter) . 'php' 
                                       . "' . str_repeat(\"\n\", substr_count('\$matches[1]', \"\n\")) .'" 
                                       . $this->_quote_replace($this->right_delimiter) 
                                       . "';") 
                                       , $source_content);

http://www.smarty.net/forums/viewtopic.php?p=85326&sid=27e3a0b8fb6de30f112f4eba25f5f567

Same Error after installation finished: http://i.imm.io/1n1VJ.jpeg

**Comment by tibistibi** [comment]
thanks for the example i had to adjust it a bit:

$source_content = preg_replace_callback($search, create_function ('$matches', "return '" 
. $this->_quote_replace($this->left_delimiter) . 'php'
. "' . str_repeat(\"\n\", substr_count('$matches[1]', \"\n\")) .'"
. $this->_quote_replace($this->right_delimiter)
. "';")
, $source_content);

**Comment by tibistibi** [comment]
and one more minor change:

        $source_content = preg_replace_callback($search, create_function ('$matches', "return '"
                                       . $this->_quote_replace($this->left_delimiter) . 'php'
                                       . "' . str_repeat(\"\n\", substr_count('\$matches[1]', \"\n\")) .'"
                                       . $this->_quote_replace($this->right_delimiter)
                                       . "';")
                                       , $source_content);

**Comment by tibistibi** [comment]
and to fix this error: preg_replace_callback(): Empty regular expression in
i added some "/" like this:

        $source_content = preg_replace_callback("/".$search."/", create_function ('$matches', "return '"
                                       . $this->_quote_replace($this->left_delimiter) . 'php'
                                       . "' . str_repeat(\"\n\", substr_count('\$matches[1]', \"\n\")) .'"
                                       . $this->_quote_replace($this->right_delimiter)
                                       . "';")
                                       , $source_content);

**Comment by apmuthu** [comment]
The original code from lines 265 to 270 in the [library/smarty/Smarty_Compiler.class.php](https://github.com/simpleinvoices/simpleinvoices/blob/master/library/smarty/Smarty_Compiler.class.php#L265) without leading whitespace is:
````
$source_content = preg_replace_callback($search, create_function ('$matches', "return '"
. $this->_quote_replace($this->left_delimiter) . 'php'
. "' . str_repeat(\"\n\", substr_count('\$matches[1]', \"\n\")) .'"
. $this->_quote_replace($this->right_delimiter)
. "';")
, $source_content);
````
The change you want to make (based on your last post) is to replace the `$search` variable in the first line above with:
````
"/".$search."/"
````
What does this fix?

**Comment by tibistibi** [comment]
i had an error. i think when $search is empty the regular exrpession was not happy. with the backslashes it worked.

**Comment by apmuthu** [comment]
What happens to search strings that contain a double quote? `addslashes()` should do the job and if `mysql_real_escape_string()` is used, then the string variable would generally take care of it. It is better to check if the `trim`med value is `empty` / zero byte string to avoid processing it in the first place if you have such a problem.

**Comment by tibistibi** [comment]
sounds all great, for me it works fine now. 

i'm not a php programmer (java) i found the above improvement on the internet.
