### ISSUE TITLE
Install fail with 2013.1.beta.8

### ISSUE THREAD

**Issue by superservidor** [simpleinvoices/simpleinvoices#208]
Hello.

I have donwloaded the version 2013.1.beta.8 in the ZIP mode and uploaded all the files to my webserver folder, created the blank db, edited the config.php  with my db data, and do a chown www-data:www-data -R -v to the folder simpleinvoices, but when i go to my site to start the install process i got a blank page, can someone help me please ?

It is part of my config.php file:

database.adapter        			        = pdo_mysql
database.utf8            			        = true
database.params.host     			= localhost
database.params.username 			= si20131b8
database.params.password 			= vuduhajan
database.params.dbname   			= zadmin_si20131b8
database.params.port       			= 3306

Heres is my PHPINFO file:
http://facturacion.superservidor.cl/simpleinvoices_2013.1.beta.8/phpinfo.php

**Comment by apmuthu** [comment]
Take the one off my gitHub master

**Comment by ghust** [comment]
When downloading the master I also get a white page. php version 5.5 is installed on my webspace.
When logging errors it gives me this:
Warning: require_once(Zend/Loader/Autoloader.php): failed to open stream: No such file or directory in /home/website/www/invoicing/include/init.php on line 10
When using the download from the official website it works immediately. 

line 10 = require_once 'Zend/Loader/Autoloader.php';

Any idea how I could fix this?

**Comment by michael-coleman** [comment]
If you want a copy of Simple Invoices for development, it has a dependency on the Zend library, you can either download files manually or resolve as per the instructions in the `readme.md` (including as a git sub module).  
If you want to install simple invoices for regular use you can get "production ready" copies - which include all the dependencies here - <http://download.simpleinvoices.org/simpleinvoices/downloads>

**Comment by ghust** [comment]
Oh, thanks!

I'll give that a try!

2015-03-27 11:37 GMT+01:00 Michael Coleman <notifications@github.com>:

> If you want a copy of Simple Invoices for development, it has a dependency
> on the Zend library, you can either download files manually or resolve as
> per the instructions in the readme.md (including as a git sub module).
>
> If you want to install simple invoices for regular use you can get
> "production ready" copies - which include all the dependencies here -
> http://download.simpleinvoices.org/simpleinvoices/downloads
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simpleinvoices/simpleinvoices/issues/208#issuecomment-86896798>
> .
>



-- 
Met Vriendelijke Groeten,

Pieter Schaek
Tel: 0478 63 34 97

**Comment by ghust** [comment]
Worked, thanks!

I was under the impression there was a bootstrap-version available? Think I saw it somewhere on github :)
