### ISSUE TITLE
Is there an anticipated Stable release coming soon?

### ISSUE THREAD

**Issue by JedMeister** [simpleinvoices/simpleinvoices#213]
Hi, I work with [TurnKey Linux](http://www.turnkeylinux.org/) and we have been producing a [SimpleInvoices software appliance](http://www.turnkeylinux.org/simpleinvoices) for some time now.

However currently there is a bug (incompatability with newer versions of php) in the (old) stable version that we have been using for our appliance. It seems that this is fixed in the newest version of SI. But there does not appear to be a stable release yet (only beta).

If this was for my personal use then I'd probably install it, test it out and decide for myself. But seeing as this is a redistributed product that others will use (many who may have never heard of SI before) I am not comfortable installing a beta...

**Comment by apmuthu** [comment]
Installing the Master codebase (aka Beta) is okay in the case of SI since reasonable care is taken to accept submissions into it.

**Comment by JedMeister** [comment]
Ok thanks for that. We may do that then although I'm still a little hesitant.

Out of interest; if the beta is stable enough for production then why not release as stable?

**Comment by apmuthu** [comment]
There are a couple of commits I need to verify and assimilate as it has too many dependencies on monolithic js libraries and we wish to avoid cdn delivery of code. Code releases are best done by Justin Kelly, the project initiator, when he deems it fit.

**Comment by JedMeister** [comment]
Thanks for the info. FWIW I've just updated our appliance build code to build from 'master' and it seems to be running nicely. :smile: So I'll close this one for now. Thanks again.
