### ISSUE TITLE
Simple invoices error while trying to run it on linux live server

### ISSUE THREAD

**Issue by Oscah3** [simpleinvoices/simpleinvoices#217]
I configured my Simple Invoice on XAMPP and uploaded it to linux server the when trying to open it it says: "Warning: require_once(Zend/Loader/ Autoloader.php): failed to open stream: No such file
or directory in /home/myusername/public_html/ manage/include/init.php on line 10 Fatal error: require_once(): Failed opening required 'Zend/Loader/Autoloader.php' (include_
path='.:/usr/lib/php:/usr/local/lib/php:./include/
class:./library/:./library/pdf:./include/') in /home/myusername/public_html/manage/include/init.php on line 10.
Please can any one solve this issue?.

**Comment by apmuthu** [comment]
In the <b>simpleinvoices/library</b> folder you will need a <b>Zend</b> subfolder with contents taken from the [Zend v1.11](https://github.com/dmelo/Zend-1.11/archive/27d7f1b3f45a436a9c795881db1d41689b8f9224.zip) project. If you had installed a release version, it would contain the Zend library but if you took the GitHub snapshot, then you will have to manually put it in.

**Comment by Oscah3** [comment]
Ok will post update after trying this out. As for I tried the Zend folder I found on XAMPP Version 1.7.3 where I was running my local installation of simple invoices and got this error ''Fatal error: Uncaught exception 'Zend_Config_ Exception' with message 'syntax error, unexpected
'!' in ./config/config.php on line 11 ' in /home/myusername/public_html/simple-invoices/library/Zend/Config/
Ini.php:184 Stack trace: #0 /home/myusername/public_
html/simple-invoices/library/Zend/Config/Ini.php(125):
Zend_Config_Ini->_loadIniFile('./config/config...') # 1 /home/username/public_html/simple-invoices/include/
init.php(131): Zend_Config_Ini->__construct('./
config/config...', 'production', true) #2 /home/
myusername/public_html/simple-invoices/index.php(31):
require_once('/home/myusername/pu...') #3 {main}
thrown in /home/myusername/public_html/simple-invoices/ library/Zend/Config/Ini.php on line 184

**Comment by apmuthu** [comment]
Install from the latest [v2013 beta 8](https://github.com/simpleinvoices/simpleinvoices/archive/2013.1.beta.8.tar.gz) release.
Then overwrite with the [snapshot from the GitHub master](https://github.com/simpleinvoices/simpleinvoices/archive/master.zip) branch.

**Comment by Oscah3** [comment]
Ok thanks I will post update once done...:-)

**Comment by Oscah3** [comment]
I did exctly what you said installed the v2013 beta 8 release and overwrited it with the snapshot but I still get this error "Fatal error: Uncaught exception 'Zend_Config_Exception' with message 'syntax error, unexpected '!' in ./config/config.php on line 11 ' in /home/oscah3/public_html/simpleinvoices/library/Zend/Config/Ini.php:182 Stack trace: #0 /home/oscah3/public_html/simpleinvoices/library/Zend/Config/Ini.php(202): Zend_Config_Ini->_parseIniFile('./config/config...') #1 /home/oscah3/public_html/simpleinvoices/library/Zend/Config/Ini.php(126): Zend_Config_Ini->_loadIniFile('./config/config...') #2 /home/oscah3/public_html/simpleinvoices/include/init.php(131): Zend_Config_Ini->__construct('./config/config...', 'production', true) #3 /home/oscah3/public_html/simpleinvoices/index.php(31): require_once('/home/oscah3/pu...') #4 {main} thrown in /home/oscah3/public_html/simpleinvoices/library/Zend/Config/Ini.php on line 182"
My server is Linux

**Comment by Oscah3** [comment]
I soleved the issue by installing it via Softaculuos autor installer, Thanks for your help

**Comment by apmuthu** [comment]
The first 13 lines of the standard <b>config/config.php</b> file are:
````
;<?php @header("location: ../index.php"); exit(0);?>
; Simple Invoices configuration file
; - refer http://www.simpleinvoices.org/config for all options

; Production site configuration data
[production]
database.adapter        			= pdo_mysql
database.utf8            			= true
database.params.host     			= localhost
database.params.username 			= root
database.params.password 			= ''
database.params.dbname   			= simple_invoices
database.params.port       			= 3306
````
As you see, there is no "!" in them. You should put in your parameters in it to suit your install - most usernames and database names in shared hosting will have your main account username as a prefix to the ones shown in your control panel.

Just compare your current config/config.php with the one you used earlier.
