### ISSUE TITLE
Certain reports not rendering (XSL)

### ISSUE THREAD

**Issue by milesgratz** [simpleinvoices/simpleinvoices#223]
I'm having a similar issue as Issue #222 where reports aren't rendering except Statement of Invoices Monthly Sales and Payments per Year. When I enable debugging in config/config.ini, I get the following when trying to load a report:

`"Fatal error: Call-time pass-by-reference has been removed in /var/www/simpleinvoices/library/phpreports/PHPReportMaker.php(274) : eval()'d code on line 140" `

**phpinfo**: [simpleinvoices_phpinfo.pdf](https://github.com/simpleinvoices/simpleinvoices/files/174046/simpleinvoices_phpinfo.pdf)

**Build process**: https://github.com/milesgratz/simpleinvoices-droplet/blob/master/build

**Comment by apmuthu** [comment]
Use a later version
https://bitbucket.org/simpleinvoices/simpleinvoices/downloads/simpleinvoices.2013.1.beta.7.zip

**Comment by milesgratz** [comment]
Thanks. Reports are working on 2013.1.beta.7.zip.
