### ISSUE TITLE
Languages not styled as expected

### ISSUE THREAD

**Issue by JPG-Consulting** [simpleinvoices/simpleinvoices#252]
Haven't gigged much into it but `es_MX` on line 87:

    $LANG['credit_card_number_encrypted'] = "Nuevo numero de tarjeta de crédito
    ";//1

It is splitted into 2 lines and regular expresions could fail to detect it... Plus that translation is not correct and it matches the next translation so something must have gone wrong during the process.

**Comment by apmuthu** [comment]
'$LANG['credit_card_number_encrypted']' had only one occurrence of the splitted line across all languages.
````
grep -r "credit_card_number_encrypted" ./lang
````

**Comment by JPG-Consulting** [comment]
I was meaning the translation message of those two lines are the same:

    $LANG['credit_card_number_encrypted'] = "Nuevo numero de tarjeta de crédito";//1
    $LANG['credit_card_number_new'] = "Nuevo numero de tarjeta de crédito";//1

No need to know spanish to know `Nuevo numero de tarjeta de crédito` cann't match `The credit card number has been encrypted and is not displayed in Simple Invoices"` and `New credit card number`.

Should be:

    $LANG['credit_card_number_encrypted'] = "El número de la tarjeta de crédito ha sido encriptado y no se muestra en Simple Invoices";//1
    $LANG['credit_card_number_new'] = "Nuevo número de tarjeta de crédito";//1

However the problem here is not as easy as you've done it in the commit... I would have sent a pull request if it was so easy to fix. There must be a bug somewhere else, as it seems a script has ruined it by pulling bad translations. 

I must remember you that translations are handled through transifex and, right now `es_MX` is ruined, just look at:
https://www.transifex.com/mattantwest/SimpleInvoices/viewstrings/#es_MX/core

Further more `lang.php` files should be synched with transifex to maintain the project consistency... so they shouldn't be edited if the synch is not possible as one could ruin the other.

**Comment by apmuthu** [comment]
How it should be is often not how it is. Transifex was used by Matt West and when some releases were made. Translations are best left to the end user with as many as 41 languages officially in SI - many have marginal differences with a few of their ilk. The text editor used to translate language files will have to be set for UTF-8 encoding without BOM for most languages.

**Comment by modir** [comment]
To say is that Matt was at this time the substitute of Justin (and there was even the idea that he would take it over). And he planned to migrate the whole translation process to Transifex because it would allow others without coding knowledge to help with the translation. From my point of view it would be a good idea to do the translations only on Transifex from now on.

**Comment by apmuthu** [comment]
Unfortunately, there is no way to obtain the translations from [Transifex](https://www.transifex.com/) without logging in. There is also no read-only username / password pair that can be used by FA to dynamically grab the latest translations on demand. [GlotPress](https://blog.glotpress.org/) too can be used.

**Comment by matt-west** [comment]
Hey everyone. Yep, we migrated translations to Transifex a few years ago. We were going to handle all of the translation files there and then pull an updated set of translations into the repo before we put out a public release. 

@apmuthu I've added you as a maintainer on the Transifex project. Let me know if anyone else needs adding.

**Comment by apmuthu** [comment]
Thanks @matt-west and I have included the Tamil translations - Native speakers of Tamil may pleas chip in to fill up the translations. There are over 20 requests for language translations that are pending there.

Where there are very few changes in language strings, they may be considered to be a patch to the primary language by "including the parent and overriding the chosen ones".
