### ISSUE TITLE
Not seeing bank name in export documents

### ISSUE THREAD

**Issue by leslieongit** [simpleinvoices/simpleinvoices#261]
I've created columns in the database table  **si_preferences** namely pref_inv_payment_bank and pref_inv_payment_bank_values both VARCHAR type and assigned a Bank and Value to the Invoice row as in below image. 
![image](https://cloud.githubusercontent.com/assets/14816994/21583094/c9127932-d079-11e6-9470-4cbd90fb9116.png)

I've also added 

> <tr><td class="" colspan="6">{$prereference.pref_inv_payment_bank|htmlsafe} {$prereference.pref_inv_payment_bank_value|htmlsafe} </td></tr>

to line 450 in file templates/invoices/default/template.tpl . This should output data from the respective columns but its not doing so. Help.

**Comment by apmuthu** [comment]
The file include/sql_queries.php has at lines 288-293:
````
function getPreference($id, $domain_id='') {
	global $LANG;
	$record = getGenericRecord('preferences', $id, $domain_id, 'pref_id');
	$record['status_wording'] = $record['status']==1?$LANG['real']:$LANG['draft'];
	$record['enabled'] = $record['pref_enabled']==1?$LANG['enabled']:$LANG['disabled'];
	return $record;
}
````

In lines 268-275:
````
function getGenericRecord($table, $id, $domain_id='', $id_field='id') {

	$domain_id = domain_id::get($domain_id);

	$record_sql = "SELECT * FROM `".TB_PREFIX."$table` WHERE `$id_field` = :id and `domain_id` = :domain_id";
	$sth = dbQuery($record_sql, ':id', $id, ':domain_id',$domain_id);
	return $sth->fetch();
}
````

Hence all fields in the specific record get returned to the template.tpl used in template.php file.
The $domain_id is overwritten in the latter function without considering if it has some non blank integer value.
Replace the said line 270:
`$domain_id = domain_id::get($domain_id);`
with
`if ($domain_id == '') $domain_id = domain_id::get($domain_id);`
