### ISSUE TITLE
Blank pages upon upload to the server

### ISSUE THREAD

**Issue by vvcares** [simpleinvoices/simpleinvoices#264]
Blank pages upon upload to the server. 
After drill-thru, found the "https://github.com/simpleinvoices/simpleinvoices.git" zip file missing of /library/Zend files.
Than separately downloaded and added inside the path - Than works fine

**Comment by apmuthu** [comment]
The Zend Library version is specific to the standard SI install and is bundled into releases but linked into the Git Repo and can be downloaded with it if the `--recursive` switch is used when cloning / fetching it.
