### ISSUE TITLE
Logo File in Template

### ISSUE THREAD

**Issue by Guenny0488** [simpleinvoices/simpleinvoices#265]
At the moment i try to create a simple template for my needs and i see that in the default template a logo variable is mentioned

`<td colspan="5"><img src="{$logo|urlsafe}" border="0" hspace="0" align="left"></td>`

How can i make use of this?
Where do place / choose my file?

Or can i hardcode the company logo within the template file?

**Comment by apmuthu** [comment]
The Biller's logos are placed in the **`templates/invoices/logos/`** folder.
The default SI Company Logo is at **`images/common/simple_invoices_logo.jpg`**
![si_billers_logo](https://cloud.githubusercontent.com/assets/2995044/21859902/70df3704-d854-11e6-8543-62b8647d3ca9.png)
