### ISSUE TITLE
Total by Aging periods report incorrect

### ISSUE THREAD

**Issue by tmtisfree** [simpleinvoices/simpleinvoices#274]
Hello,

If you go to the "Total by Aging periods" report page [1] on the Simple Invoices website, you can see the same Paid amount is reported in both periods 0-15 and 90+, which means the Paid total and the entire Owing column are wrong.

Edit: after the Simple Invoices website resets, just add a new invoice and pay it fully, then go  the "Total by Aging periods" report page to see this payment duplicated on all periods.

[1] http://demo.simpleinvoices.org/index.php?module=reports&view=report_debtors_aging_total

**Comment by apmuthu** [comment]
It is perfectly okay.
`90+` should be read as `0 to 90+` as far as the first two columns are concerned for the second row and the actual aged value (`Aging`) will be the difference in 90+ days for it.

**Comment by tmtisfree** [comment]
According to logic, common sense, proper accounting rules and all other SI reports which deal with aging (see eg [2]) 90+ means equal and more than 90 days. Paid/owing amounts at 0-14 days have nothing to do in the 90+ row as link [2] demonstrates : Paid/owing totals in [1] are wrong. Additionally, [2] lists and accounts for draft invoices, which is incorrect as well.

[1] http://demo.simpleinvoices.org/index.php?module=reports&view=report_debtors_by_aging

**Comment by apmuthu** [comment]
Presumably, the devs at SI used their idea of "common sense" to incorporate the Opening Balance and then the 90+ days values so that the complete dues are listed.

Your point is well taken though.

@justinkelly : What say you?
