### ISSUE TITLE
How do I know which version of simpleinvoices I currently use ?

### ISSUE THREAD

**Issue by aleifuu** [simpleinvoices/simpleinvoices#278]
simpleinvoices is a great software to use for small-business owner. I have downloaded, installed on my raspberry pi and everything is running well .. well, except for the blank reports problem that i'm having and seems everyone else must've countered. php5-xsl is installed and is enabled, so it's not a xsl problem 

I'd like to know how can I know/check which SI version I'm currently using, as there is no year/revision number information I can get out of the package 

I'm not sure If i'm using the bleeding edge version, 2011, stable, 2010 ( git's) or the one from simpleinvoices.org

Safe to say I forgot which file I download and install that time

**Comment by apmuthu** [comment]
Check the `config.php` file for the value of `version.name` which in the latest is `2013.1.beta.8`,

**Comment by aleifuu** [comment]
Ok. thanks for that

sorry, I'm a little new to open-source world. would usually find that information from README or changelog

I have now discovered that I'm using the 2011.1 - stable version 

but still encounter same error

time to dig deeper for some more information

**Comment by aleifuu** [comment]
and solved by following this issue #65 . Closed =) !
