### ISSUE TITLE
Simple invoices PDF blank with new PHP7

### ISSUE THREAD

**Issue by vvcares** [simpleinvoices/simpleinvoices#279]
Hi muthu,
is there any updates for PHP7 ?
We currently upgraded to PHP7 then our SI pdf, email etc getting blank pages. Kindly waiting for your valuable advises.

**Comment by apmuthu** [comment]
The core SI and my fork/repo will not be supporting PHP7. There are other forks that support it - check them out.

In most instances it will need the new Array() syntax and the conversion of all constructors and destructors for all class definitions to the new syntax.

**Comment by vvcares** [comment]
Hi bro muthu,
ok noted, Thank you
