### ISSUE TITLE
Export data from repetitive customer

### ISSUE THREAD

**Issue by azmim** [simpleinvoices/simpleinvoices#280]
I am planning to have details of regular by sort the most customer having most invoice created under their name. At this moment I able to export si_customers tables to excel, however I cant get the linkage of the invoice to the customer.

I prefer to export to excel so that i can pivot & sort the data.

Thank you & Please advise.

**Comment by apmuthu** [comment]
Home => All Reports => Sales => Sales By Customer

All report files are in `modules/reports` folder.

The file `modules/reportsreport_sales_customers_total.php' is referred to in the url by: `http://domain.tld/path_to_si/index.php??module=reports&view=report_sales_customers_total`

You can modify the sql to suit your needs possibly using group by, sum, count, max, order by xxx desc, etc.

**Comment by azmim** [comment]
Thank you apmuthu. I'll try to dig from there.
