### ISSUE TITLE
Generate pdf

### ISSUE THREAD

**Issue by xstocler** [simpleinvoices/simpleinvoices#284]
On the page that lists all created invoices, shows the button to generate pdf.
I am trying to add new fields to the pdf file.
I can not understand how it is generated

**Comment by apmuthu** [comment]
The URL to create a PDF will be like:
`index.php?module=export&view=invoice&id=3&format=pdf`

The `modules/export/invoice.php` gets the url parameters and then goes to the `pdf.php` which acquires the invoice in html format first.

The field data was acquired from `modules/invoices/invoice.php` and assigned to the template.
The data is now in `modules/invoices/xml.php`

The `library/pdf/html2ps.php` is there to make it a pdf file.

The actual template that displays the html (which becomes the PDF) is at:
`templates/invoices/export/template.tpl`

**Comment by xstocler** [comment]
I am trying to change any field of the file:
`templates/invoices/export/template.tpl`

nothing changes in the generated pdf file

**Comment by apmuthu** [comment]
The `template` file needs to be given the variables from the `xml` file and check out it's parent files for the variables too - both `invoice.php` files as well. The variables in the template file are enclosed in curly braces along with modifier functions after the pipe character within it.

**Comment by xstocler** [comment]
I think I'm a bit slow, lol.
I am not wanting to remove the customized product field 4 from pdf
keeping the others.

Can you help me?
The field is filled in

**Comment by apmuthu** [comment]
You can pass variables thru the URL itself or have it taken from a file. Provide a screenshot of what you want and from which output.

**Comment by xstocler** [comment]
File generated with fields
I want to remove the fields indicated that would be the custom field of product 4

![image](https://user-images.githubusercontent.com/29358084/34388210-8f6dba3c-eb19-11e7-8505-db48fd64dd3c.png)

**Comment by apmuthu** [comment]
Comment out lines 269 and 270 in `templates/invoices/default/template.tpl`
![si_mod_for_suppressing_item_cf4](https://user-images.githubusercontent.com/2995044/34390304-fbbe1e70-eb64-11e7-8f22-688e1b2cf855.png)

**Comment by xstocler** [comment]
Thank you very much
now I can change other things.
