### ISSUE TITLE
Create a link on the invoice screen

### ISSUE THREAD

**Issue by xstocler** [simpleinvoices/simpleinvoices#286]
I'm trying to figure out where I can enter a new link on the screen below

![image](https://user-images.githubusercontent.com/29358084/36938382-7d360d14-1eff-11e8-8e79-26dc94325c7b.png)

I want to create a page with href with the invoice id

Only I can not find the location of the code.

Could you help me, please?

**Comment by apmuthu** [comment]
Have a look from line 44 onwards in `modules/invoices/xml.php` the html output of which is like:
![si_invoicelisting](https://user-images.githubusercontent.com/2995044/36945413-d912b1f8-1fd3-11e8-8602-9e3e3cb6f34e.png)

**Comment by xstocler** [comment]
thank you so much
