### ISSUE TITLE
simpleinvoice are clodes?

### ISSUE THREAD

**Issue by OMG809** [simpleinvoices/simpleinvoices#295]
Hi. I try to see the install guide on the site, nut simpleinvoice.org are closed. The support for this web application is closed?

**Comment by apmuthu** [comment]
Support is in the forum and wiki.
https://simpleinvoices.io/
https://web.archive.org/web/20180410210531/http://simpleinvoices.org:80/install

**Comment by jmclaren7** [comment]
Hey @apmuthu, I'm a little out of the loop and I just want to make sure I understand. Has the website been officially shutdown and what is the relationship with simpleinvoices.io ?

**Comment by apmuthu** [comment]
There appears to be **no link** between the SimpleInvoices project and the domain https://simpleinvoices.io/

The simpleinvoices.org domain has not been renewed by the project lead and hence the Web Archived version.

**Comment by jmclaren7** [comment]
So why did you mention simpleinvoices.io?

**Comment by apmuthu** [comment]
It is an example of SI usage for screen comparisons and extraction of CSS and other goodies for further development. Maybe the lead dev assists them - not known. If it appears to be commercial, I'll remove it.
