### ISSUE TITLE
All the discussion/contact methods seem to be gone

### ISSUE THREAD

**Issue by ghost** [simpleinvoices/simpleinvoices#297]
"Get Started" , Demo, Blog, etc. on the simpleinvoices.org domain are non-functional (at least for me).

I really like simpleinvoices and want to help it continue. Is there any sort of communication method for the users & devs?

**Comment by apmuthu** [comment]
Hopefully they will be reconstructed soon.

**Comment by apmuthu** [comment]
[Getting Started](https://web.archive.org/web/20161119074239/http://www.simpleinvoices.org/go)
[Demo](https://web.archive.org/web/20161118222133/http://demo.simpleinvoices.org:80/)
[Blog](https://web.archive.org/web/20161119001455/http://www.simpleinvoices.org:80/blog)
[Forum](https://web.archive.org/web/20161119001614/http://forum.simpleinvoices.org/)
