### ISSUE TITLE
PDF not exporting

### ISSUE THREAD

**Issue by theamanjs** [simpleinvoices/simpleinvoices#302]
I've installed simple invoices on my machine and I've faced an issue that when I tried to export pdf and what I get is a new tab got opened and nothing happened. The new tab just got processed and stopped. Please fix this issue so that pdf should be exported. Rest of the export options are working very well.

**Comment by apmuthu** [comment]
What is the platform and version of OS,PHP,MySQL,Apache of your server and client browser?
Have you set the file and folder permissions for those folders that need to allow writing by the webserver process?
Kindly refer the [wiki](https://github.com/simpleinvoices/simpleinvoices/wiki) for known issues and install instructions.
