### ISSUE TITLE
PDF Export wrong format

### ISSUE THREAD

**Issue by pixel-penguin** [simpleinvoices/simpleinvoices#303]
After updating to the latest version of simple invoices, there seems to be an issue when exporting to pdf. 

I"m running CPANEL with php 5.6, all the extension enabled (also made sure GD is enabled)

I checked manually up until the point when the template was generated and echo and die to display the html. It looked 100%. As soon as the PDF gets generated the pdf looks horrible (and logo doesnt display)

Attached is a sample of the pdf
[Invoice_215 (14).pdf](https://github.com/simpleinvoices/simpleinvoices/files/3612801/Invoice_215.14.pdf)

Can anyone shed some info on this situation?

**Comment by apmuthu** [comment]
Which version of SI were you on when it last worked properly?
Where did you get your current version - use the [Git Master version](https://github.com/simpleinvoices/simpleinvoices/archive/master.zip)
Check for the presence of the logo in the right path and the file and folder permissions especially for the temp folder. Also see if there are any PHP errors seen after enabling error_reporting in php.ini

**Comment by pixel-penguin** [comment]
_Check for the presence of the logo in the right path and the file and folder permissions especially for the temp folder._ -- I Have checked this
 _Also see if there are any PHP errors seen after enabling error_reporting in php.ini - I have done this as well, no errors 
I even tried the following inside index.ph
`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);`

The older version is still on my old server. Where can check the version number? Also, I have used that Git Master Version you're referring to.

**Comment by apmuthu** [comment]
The version is listed under `version.name` in `config/config.ini` in your old stable `2011.1 - stable` and the new one is listed in `config/config.php` as `2013.1.beta.8`

Check the various constants in `config/define.php` to enable debugging.

The layout is missing the css file which styles the invoice. Check if you have customised the Invoice templates which may not be overwritten with the defaults in the new one.

Line 230 in your `library/pdf/output.pcl.class.php` is missing a semicolon at the end.

There are some `eregi` to `preg_match` replacements that may be in order for PHP 5.6.

Try to run the new SI code in PHP 5.3 / 5.4 first and then check on PHP 5.6.

There appear to be some case sensitive php smarty template naming of variables that need to match the table schema. eg., lines 242,243 in `extras/invoice_grouped/templates/invoices/grouped/template.tpl` in your old one to match against the new schema.

Try a fresh install of SI latest and see if all works in it with new schema and no data to start with.

**Comment by pixel-penguin** [comment]
I will try to install a new copy clean. Will I be able to import the old tables into the new DB? I'm not sure if the CSS is the issue. When I go to `include/class/export.php`
and enter the following on line 270;
`echo $this->getData();
die();`

![image](https://user-images.githubusercontent.com/8964456/64912550-4e632300-d731-11e9-91d2-73efe084c2ce.png)


As you can see the styling looks 100%. So from there somewhere it messes up the styling when converting the pdf. I've also tried redownloading and replacing https://github.com/triple-j/html2ps files. No luck.

If the template was the issue, wouldn't the styling in the screenshot I sent also be messed up?

**Comment by pixel-penguin** [comment]
Sorry, I forgot to add, I tried this on both PHP 5.5 and 5.6. I don't have PHP 5.3 or 5.4 installed on my server. If you say the chances are great that it will fix my issue, I'll install it on my server.

**Comment by pixel-penguin** [comment]
I tried installing a completely new project (without importing old DB). I filled in a couple of new records and did an export. Exactly the same results. PDF export has some weird format. I am stumped. My only guess is that it's something on my server that causes this.

**Comment by pixel-penguin** [comment]
I found the issue, and I'm pasting it here. The issue was on my server, my cpanel on standard didn't allow "allow_url_include" etc. Which caused everything to work fine except the pdf conversion.

I enabled everything and it works fine now.

![image](https://user-images.githubusercontent.com/8964456/65309610-b92ab900-db8c-11e9-9a9d-b2c05329be9e.png)

**Comment by apmuthu** [comment]
Thanks.
