### ISSUE TITLE
Really struggling to install

### ISSUE THREAD

**Issue by mcsnoogins** [simpleinvoices/simpleinvoices#304]
Apache server that had simple invoices running on it before, had been migrated from a different VPS and picked up an issue with the export to PDF not displaying the company logo (worked fine on the old VPS, tried all the suggestions, gd2 installed and enabled etc). Figured something got corrupted or permissions were messed up during the transfer and thought i'd just delete the invoice folder and db and install from fresh to see if the problem still occurred. Can't get past "This page isn’t working invoicing.revolutionaryit.co.uk is currently unable to handle this request.
HTTP ERROR 500", have created new blank database, uploaded master.zip and extracted to folder called invoice which has external access as before.  Can't get anywhere with installing, have edited config.ini with blank database details, removed a - from the database password at one point as found someone online saying that the config.ini file doesn't agree with and special characters in it. Database has a _ in the name as does the user but can't remove them as they are system provided when database and user are created.  Any help would be greatly appreciated.

**Comment by apmuthu** [comment]
State the versions of SI, PHP, MySQL, Apache on both the old and the new VPSes.

Check the Apache Error logs and try with debug on.

If not technically competent, seek professional assistance with backups of the mysql db and the SI deployment folder.

You have not removed the `phpinfo.php` file after installation. The [output](https://invoicing.revolutionaryit.co.uk/phpinfo.php) of the said file shows that you are using `PHP 7.1` and this version of SI is not tweaked for it yet. Choose any of the other forks that support it.

**Comment by mcsnoogins** [comment]
Have bypassed the new issue by restoring to what my original problem was.  Will post new for current issue.
