### ISSUE TITLE
Reports "Statement of Invoices" shows even quotations instead of unpaid invoices only

### ISSUE THREAD

**Issue by Oscah3** [simpleinvoices/simpleinvoices#310]
How can I only show unpaid invoices instead of showing all the other invoice preferences? Your swift response will be much appreciated on this.

Thanks

**Comment by apmuthu** [comment]
![All_Invoices](https://user-images.githubusercontent.com/2995044/80384187-3310e680-88c2-11ea-8a1c-0e2c524047b4.png)

Only **Due** *Invoices* - Use the filter **Due** and **Real**:
![Unpaid_Invoices](https://user-images.githubusercontent.com/2995044/80384474-8aaf5200-88c2-11ea-9430-8dfddbaa7274.png)

**Comment by Oscah3** [comment]
I mean on on this URL index.php?module=statement&view=index it then displays even quotations, receipts, estimates while I need only invoices to display. My invoice preference ID is 1 if anyone could help and customize the code to only show invoice preference 1 not all preferences.

Refer Line 155 of `templates/default/statement/index.tpl`
https://github.com/simpleinvoices/simpleinvoices/blob/master/templates/default/statement/index.tpl#L155

Thanks

**Comment by Oscah3** [comment]
[index.zip](https://github.com/simpleinvoices/simpleinvoices/files/4547683/index.zip)

**Comment by Oscah3** [comment]
I have figured out a way to fix it. I have changed `.preference` on line 155 to `.real` and it only shows invoices.

Thanks @apmuthu

**Comment by apmuthu** [comment]
Your change may prevent you from seeing non-invoice records.
Also, you will still see the paid invoices as well.
You may have to replace `.real` with `.due` for the unpaid invoices. and make sure you have it in the proper place as there are 2 instances on the same line.

**Comment by Oscah3** [comment]
Thanks for the tip seems to work!
