### ISSUE TITLE
Call to undefined method FPDF::GetFontAscender()

### ISSUE THREAD

**Issue by ArtDecoded** [simpleinvoices/simpleinvoices#313]
Hi, I wonder if you have any idea how to solve this error :(

`Fatal error: Call to undefined method FPDF::GetFontAscender() in /Applications/XAMPP/xamppfiles/htdocs/simpleinvoices/library/pdf/output.fpdf.class.php on line 154`

---
Line 154 of that file says:
return $this->pdf->GetFontAscender($name, $encoding);

I made a copy of my simpleinvoices to my local using xampp with PHP 5.6. When I try to generate the PDF or send the email I get this error. I know there's an issue with FPDF in with PHP 7 but I have 5.6.

I tried to find in Google something related to this error but nothing comes up.

Everything so far seems to work properly except for this :(

Thanks for your help.
Pablo Alvarado

**Comment by apmuthu** [comment]
Line 4 of the said file includes the file that has the necessary class method (function). In case the value of the constant `HTML2PS_DIR` is wrong or the file pdf.fpdf.php is missing in that location, this problem would arise. In 2008, the location of the `library/pdf` folder was changed.

Which version of SimpleInvoices are you using and which location did you take it from?

Verify that you have the said library file `library/pdf/pdf.fpdf.php` and that it has the following method as lnes 1529-1533 in it:
````
    function GetFontAscender($name, $encoding) {
      $fontkey = $this->_MakeFontKey($name, $encoding);
      $this->_LoadFont($fontkey, $name, $encoding, '');
      return $this->fonts[$fontkey]['desc']['Ascent'] / 1000;
    }
````

**Comment by ArtDecoded** [comment]
Thank you very much @apmuthu  and taking your valuable time to reply my question.

So I'm using Version 2011.1

So in library/pdf/output.fpdf.class.php in line 4 I have:
`require_once(HTML2PS_DIR.'pdf.fpdf.php');`

In library/pdf/pdf.fpdf.php I have indeed exactly in the lines you mention with the function GetFontAscender() as you pointed.

I also tried changing the "require_once" in library/pdf/output.fpdf.class.php like this but gives exactly the same error:
```
require_once(HTML2PS_DIR.'fpdf/fpdf.php');
require_once(HTML2PS_DIR.'fpdf/font/makefont/makefont.php');

```
About your question about from wich location I took it from: 
I had a working copy (version 2011.1) in my hosting service (indeed is working and doesn't give any issues) but I will need to update to PHP 7 because other applications are crashing. Some time ago I tried to updated to PHP 7 but then I realize about the issue with the PDF generation so I rolled back to PHP 5.6 and at this moment Simple Invoices works fine. But now I'm being pressured to move to PHP because all others applications are crashing.

So my plan right now was/is to run Simple Invoices locally with PHP 5.6 instead of buying other hosting. So I downloaded that copy and I'm running it locally as I said with PHP 5.6. The only error I have is this one I'm reporting but this error is not happening in the copy of  my hosting.

However I also downloaded  the same version 2011.1 from https://bitbucket.org/simpleinvoices/simpleinvoices/downloads/simpleinvoices.2011.1.zip, I just changed the config.ini to use my database but the result was exactly the same.

I don't think is something wrong in SimpleInvoices. I think is something more, maybe in my PHP configuration or XAMPP.

Thank you!

**Comment by apmuthu** [comment]
Use the [GitMaster version](https://github.com/simpleinvoices/simpleinvoices/archive/master.zip) (with the appropriate library/Zend files) on your Windows PHP 5.6 and see if it works as desired or scale back to PHP 5.4 with [XAMPP 1.8.2.5](https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/1.8.2/xampp-win32-1.8.2-5-VC9-installer.exe/download) (not 1.8.2.6). The GitMaster version is `2013.1.beta.8`.

**Comment by ArtDecoded** [comment]
Is Mac but,  tried all you mentioned.  BTW I'm surprised how fast is 2013.1.beta.8 seems to work great except for the same error of GetFontAscender in my computer.

XAMPP 1.8.2.5 doesn't seem to get installable on Mojave.

In the end I decided to bought a small hosting with 5.6 that works also with 2013.1. I'll work with that.

I appreciate your time @apmuthu . Thank you :)
Pablo
